### ISSUE TITLE
#3 관리자페이지 수정 요청

### ISSUE THREAD

**Issue by hobit22** [A-Chool/BE#30]
1. token front 단에 뿌리기
2. User Entity 가입일자 추가

**Comment by hyun-woong** [comment]
1. 토큰을 프로트에 뿌린다는게 어떤 의미일까요?
2. 가입일자는 저희 TimeStamped 상속해서 쓰고 있어서, createdAt 을 가입일자로 써도 되지 않을까요?
필요 요청 하시면, 같이 끼워 보내드리기만 하면 될 것 같습니다.
