### ISSUE TITLE
Log 남기기

### ISSUE THREAD

**Issue by hobit22** [A-Chool/BE#98]
Example

Controller 
log.info("/admin/userList");

Service
log.info("getMemberList" + memberList);

다른 github 보다가 이런식으로 log를 남기길래 저희도 log를 찍으면 관리면에서 좋을것 같습니다

**Comment by hyun-woong** [comment]
method 도 같이 적기

**Comment by hyun-woong** [comment]
log.info("test: {}", test) 사용해서 적기

**Comment by hyun-woong** [comment]
개선 완료했습니다.

**Comment by hobit22** [comment]
고생하셨습니다 👍
